---
options:
  substitutionOption: ALLOW_LOOSE
  dynamicSubstitutions: true

images:
  - $_IMAGE_NAME

# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
steps:
  - id: build-maki-discord
    name: docker
    args:
      - build
      - "--no-cache"
      - "-t=$_IMAGE_NAME"
      - "-f=./Dockerfile2"
      - .

  - id: push-maki-discord
    name: docker
    args:
      - push
      - $_IMAGE_NAME
