# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
steps:
  - id: build-maki-cameraman
    name: docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - $_IMAGE_NAME
      # - "-f ./docker/Dockerfile"
      - .

  - id: push-maki-cameraman
    name: docker
    args:
      - push
      - $_IMAGE_NAME

  - id: deploy-maki-cameraman
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=$_IMAGE_NAME"
      - "--region=$_DEPLOY_REGION"
      - "--quiet"

images:
  - $_IMAGE_NAME

options:
  substitutionOption: ALLOW_LOOSE
  dynamicSubstitutions: true
