steps:
  - name: gplane/pnpm:8
    entrypoint: pnpm
    args: ["install", "-r"]
    dir: "./packages/@nakayoshi/maki-cameraman"

  - name: gplane/pnpm:8
    entrypoint: pnpm
    args: ["run", "-r", "build"]
    dir: "./packages/@nakayoshi/maki-cameraman"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "functions",
        "deploy",
        "maki-cameraman",
        "--entry-point=main",
        "--runtime=nodejs18",
        "--trigger-http",
        "--allow-unauthenticated",
      ]
    dir: "./packages/@nakayoshi/maki-cameraman"
