---
options:
  substitutionOption: ALLOW_LOOSE
  dynamicSubstitutions: true

# availableSecrets:
#   secretManager:
#     - versionName: projects/$PROJECT_ID/secrets/${_MAKI_DISCORD_TOKEN_KEY}/versions/latest
#       env: DISCORD_TOKEN
#     - versionName: projects/$PROJECT_ID/secrets/${_MAKI_OPENAI_API_KEY}/versions/latest
#       env: OPENAI_API_KEY

images:
  - $_IMAGE_NAME

# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
# https://cloud.google.com/build/docs/securing-builds/use-secrets?hl=ja#access-utf8-secrets
steps:
  - id: build
    name: docker
    args:
      - build
      - "--no-cache"
      - "-t=$_IMAGE_NAME"
      - "-f=./packages/@nakayoshi/maki-discord/Dockerfile"
      - .

  - id: push
    name: docker
    args:
      - push
      - $_IMAGE_NAME

  - id: deploy
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    # secretEnv:
    #   - DISCORD_TOKEN
    #   - OPENAI_API_KEY
    args:
      - compute
      - instances
      - update-container
      - $_SERVICE_NAME
      - "--container-image=$_IMAGE_NAME"
      - "--zone=$_DEPLOY_ZONE"
      - "--quiet"

  # https://stackoverflow.com/questions/62103365/how-to-deploy-container-to-gce-by-updating-container-image
  - id: prune-docker-images
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - compute
      - ssh
      - $_SERVICE_NAME
      - "--zone=$_DEPLOY_ZONE"
      - "--command=docker system prune -f -a"
      - "--quiet"
